# Logic Gate XOR with NN without libraries

## Epoch 1

In [140]:
import numpy as np

In [141]:
x1 = np.array ([0, 0, 1, 1])
x2 = np.array([0, 1, 0, 1])
yd = np.array([0, 1, 1, 0])

In [142]:
w13 = np.random.uniform(0, 1)

w35 = np.random.uniform(0, 1)

w45 = np.random.uniform(0, 1)

w24 = np.random.uniform(0, 1)

w23 = np.random.uniform(0, 1)

w14 = np.random.uniform(0, 1)


In [143]:
theta3 = np.random.uniform(0, 1)
theta4 = np.random.uniform(0, 1)
theta5 = np.random.uniform(0, 1)

In [144]:
theta3

0.3800845054014922

In [145]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

sigmoid(0)

0.5

In [146]:
def S_diff(x):

    a = (sigmoid(x)) * (1-sigmoid(x))

    return a

S_diff(7)

0.000910221180121784

# Forward Propagation

In [147]:
y3 = sigmoid((x1*w13 + x2*w23) - theta3)
y3

array([0.40610652, 0.58194192, 0.51293401, 0.68191413])

In [148]:
y4 = sigmoid((x1*w14 + x2*w24) - theta4)
y4

array([0.29961468, 0.41963617, 0.39426746, 0.52384621])

In [149]:
y5 = sigmoid((y3*w35 + y4*w45) - theta5)
y5

array([0.51452017, 0.57158714, 0.55187357, 0.60735973])

# Error Calculation

In [150]:
error = yd - y5
error

array([-0.51452017,  0.42841286,  0.44812643, -0.60735973])

# Backpropagation

In [151]:
delta5 = S_diff(y5) * error
delta5

array([-0.12047895,  0.09881044,  0.10391643, -0.13865502])

In [152]:
delta4 = w45 * delta5 * S_diff(y4)
delta4

array([-0.01391805,  0.01117377,  0.01181116, -0.01530571])

In [153]:
delta3 = w35 * delta5 * S_diff(y3)
delta3

array([-0.02853017,  0.02242429,  0.0240217 , -0.03051931])

# Parameter Updates

In [154]:
alpha = np.random.uniform(0, 1)
alpha

0.556749373622459

In [155]:
delta_w35 = alpha * y3 * delta5

delta_w45 = alpha * y4 * delta5

delta_w13 = alpha * x1 * delta3

delta_w23 = alpha * x2 * delta3

delta_w14 = alpha * x1 * delta4

delta_w24 = alpha * x2 * delta4

In [156]:
delta_w23

array([-0.        ,  0.01248471,  0.        , -0.01699161])

In [157]:
d_theta5 = alpha * (-1) * delta5
d_theta4 = alpha * (-1) * delta4
d_theta3 = alpha * (-1) * delta3

In [158]:
d_theta3

array([ 0.01588415, -0.01248471, -0.01337407,  0.01699161])

## Epoch 2

In [160]:
w35 = delta_w35 + w35

w45 = delta_w45 + w45

w13 = delta_w13 + w13

w23 = delta_w23 + w23

w14 = delta_w14 + w14

w24 = delta_w24 + w24

In [161]:
theta5 = d_theta5 + theta5
theta4 = d_theta4 + theta4
theta3 = d_theta3 + theta3

# Forward Propagation with adjusted parameters

In [162]:
y3 = sigmoid((x1*w13 + x2*w23) - theta3)
y3

array([0.4022813 , 0.5880039 , 0.51961386, 0.67075627])

In [163]:
y4 = sigmoid((x1*w14 + x2*w24) - theta4)
y4

array([0.29799114, 0.4226693 , 0.39741269, 0.51746612])

In [164]:
y5 = sigmoid((y3*w35 + y4*w45) - theta5)
y5

array([0.49238345, 0.59371379, 0.57411546, 0.57169512])

In [165]:
error2 = yd - y5
error2

array([-0.49238345,  0.40628621,  0.42588454, -0.57169512])

In [166]:
error

array([-0.51452017,  0.42841286,  0.44812643, -0.60735973])

## Epoch 3

In [ ]:
w35 = delta_w35 + w35

w45 = delta_w45 + w45

w13 = delta_w13 + w13

w23 = delta_w23 + w23

w14 = delta_w14 + w14

w24 = delta_w24 + w24

In [ ]:
theta5 = d_theta5 + theta5
theta4 = d_theta4 + theta4
theta3 = d_theta3 + theta3